import type { Lead, LeadNote, Task, AIMessage, ActivityLog, SubscriptionPlan, Company, User } from './types';

const now = () => new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

export const seedCompany: Company = {
  id: 'cmp_demo',
  name: 'Northwind Studio',
  industry: 'Creative Services',
  website: 'northwind.studio',
  size: '5–10',
  created_at: daysAgo(120),
};

export const seedUser: User = {
  id: 'usr_demo',
  company_id: 'cmp_demo',
  email: 'demo@northwind.studio',
  name: 'Alex Rivera',
  role: 'owner',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=faces',
  created_at: daysAgo(120),
};

export const seedLeads: Lead[] = [
  {
    id: 'ld_01',
    company_id: 'cmp_demo',
    name: 'Sarah Chen',
    email: 'sarah@acme.io',
    phone: '+1 (415) 555-2018',
    company: 'Acme Robotics',
    source: 'LinkedIn',
    status: 'Qualified',
    deal_value: 24000,
    notes: 'Interested in our annual brand retainer. Decision by end of Q2.',
    next_followup_at: daysAhead(2),
    owner_id: 'usr_demo',
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
  },
  {
    id: 'ld_02',
    company_id: 'cmp_demo',
    name: 'Marcus Patel',
    email: 'marcus@brightlabs.com',
    phone: '+1 (212) 555-7711',
    company: 'Brightlabs',
    source: 'Referral',
    status: 'Proposal Sent',
    deal_value: 48500,
    notes: 'Needs SOC2 documentation before signing. Sent proposal Tuesday.',
    next_followup_at: daysAhead(1),
    owner_id: 'usr_demo',
    created_at: daysAgo(14),
    updated_at: daysAgo(2),
  },
  {
    id: 'ld_03',
    company_id: 'cmp_demo',
    name: 'Priya Desai',
    email: 'priya@harborhealth.com',
    phone: '+1 (617) 555-3344',
    company: 'Harbor Health',
    source: 'Website',
    status: 'New',
    deal_value: 12000,
    notes: 'Filled out demo form last night. Wants help with patient onboarding emails.',
    next_followup_at: daysAhead(0),
    owner_id: 'usr_demo',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'ld_04',
    company_id: 'cmp_demo',
    name: 'David Okafor',
    email: 'd.okafor@craftworks.co',
    phone: '+1 (310) 555-8821',
    company: 'Craftworks Co.',
    source: 'Cold Outreach',
    status: 'Contacted',
    deal_value: 8500,
    notes: 'Replied positively to our intro email. Wants pricing details.',
    next_followup_at: daysAhead(3),
    owner_id: 'usr_demo',
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  {
    id: 'ld_05',
    company_id: 'cmp_demo',
    name: 'Elena Volkov',
    email: 'elena@mistral-finance.com',
    phone: '+1 (646) 555-1290',
    company: 'Mistral Finance',
    source: 'Event',
    status: 'Won',
    deal_value: 62000,
    notes: 'Closed at SaaStr after 3 follow-ups. Kickoff next Monday.',
    next_followup_at: null,
    owner_id: 'usr_demo',
    created_at: daysAgo(28),
    updated_at: daysAgo(3),
  },
  {
    id: 'ld_06',
    company_id: 'cmp_demo',
    name: 'Tomás Beltrán',
    email: 'tomas@lumenco.io',
    phone: '+34 91 555 0091',
    company: 'Lumen Co.',
    source: 'Ads',
    status: 'Lost',
    deal_value: 18000,
    notes: 'Went with an in-house build. Revisit in 6 months.',
    next_followup_at: null,
    owner_id: 'usr_demo',
    created_at: daysAgo(36),
    updated_at: daysAgo(10),
  },
  {
    id: 'ld_07',
    company_id: 'cmp_demo',
    name: 'Hannah Bauer',
    email: 'h.bauer@orbitware.com',
    phone: '+49 30 555 0334',
    company: 'Orbitware',
    source: 'LinkedIn',
    status: 'Contacted',
    deal_value: 32000,
    notes: 'CTO loved the demo. Waiting on her CFO.',
    next_followup_at: daysAhead(4),
    owner_id: 'usr_demo',
    created_at: daysAgo(11),
    updated_at: daysAgo(4),
  },
  {
    id: 'ld_08',
    company_id: 'cmp_demo',
    name: 'Jordan Lee',
    email: 'jordan@maple.studio',
    phone: '+1 (415) 555-9981',
    company: 'Maple Studio',
    source: 'Referral',
    status: 'Qualified',
    deal_value: 15500,
    notes: 'Boutique agency, looking for white-label solution.',
    next_followup_at: daysAhead(5),
    owner_id: 'usr_demo',
    created_at: daysAgo(6),
    updated_at: daysAgo(2),
  },
  {
    id: 'ld_09',
    company_id: 'cmp_demo',
    name: 'Amelia Wright',
    email: 'a.wright@kindrclub.com',
    phone: '+1 (917) 555-2210',
    company: 'Kindr Club',
    source: 'Website',
    status: 'New',
    deal_value: 6500,
    notes: 'Small business, simple needs. Could close fast.',
    next_followup_at: daysAhead(0),
    owner_id: 'usr_demo',
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
];

export const seedNotes: LeadNote[] = [
  { id: 'nt_01', lead_id: 'ld_01', author_id: 'usr_demo', author_name: 'Alex Rivera', body: 'Had a 30min discovery call. Sarah is the decision maker. Pain point: their internal sales ops team is 1 person and drowning.', created_at: daysAgo(2) },
  { id: 'nt_02', lead_id: 'ld_01', author_id: 'usr_demo', author_name: 'Alex Rivera', body: 'Sent over the proposal deck. They want to compare against Salesforce Essentials.', created_at: daysAgo(1) },
  { id: 'nt_03', lead_id: 'ld_02', author_id: 'usr_demo', author_name: 'Alex Rivera', body: 'Marcus loved the AI follow-up demo. Forwarded to procurement.', created_at: daysAgo(3) },
  { id: 'nt_04', lead_id: 'ld_03', author_id: 'usr_demo', author_name: 'Alex Rivera', body: 'New inbound from website. Need to qualify ICP fit.', created_at: daysAgo(1) },
];

export const seedTasks: Task[] = [
  { id: 'tsk_01', lead_id: 'ld_01', title: 'Send case study deck', description: 'Healthcare vertical case studies', status: 'Pending', priority: 'High', due_at: daysAhead(1), created_at: daysAgo(1) },
  { id: 'tsk_02', lead_id: 'ld_02', title: 'Follow up on SOC2 docs', status: 'Pending', priority: 'High', due_at: daysAhead(0), created_at: daysAgo(2) },
  { id: 'tsk_03', lead_id: 'ld_03', title: 'Qualifying call', description: '15-min discovery', status: 'Pending', priority: 'Medium', due_at: daysAhead(0), created_at: daysAgo(1) },
  { id: 'tsk_04', lead_id: 'ld_04', title: 'Send pricing sheet', status: 'Done', priority: 'Medium', due_at: daysAgo(1), completed_at: daysAgo(0), created_at: daysAgo(3) },
  { id: 'tsk_05', lead_id: 'ld_07', title: 'Schedule CFO intro', status: 'Pending', priority: 'High', due_at: daysAhead(4), created_at: daysAgo(2) },
  { id: 'tsk_06', lead_id: 'ld_08', title: 'White-label feature walkthrough', status: 'Pending', priority: 'Low', due_at: daysAhead(5), created_at: daysAgo(1) },
  { id: 'tsk_07', lead_id: 'ld_05', title: 'Kickoff prep', status: 'Pending', priority: 'Medium', due_at: daysAhead(7), created_at: daysAgo(2) },
  { id: 'tsk_08', lead_id: 'ld_01', title: 'Review proposal feedback', status: 'Pending', priority: 'Medium', due_at: daysAgo(1), created_at: daysAgo(3) },
];

export const seedAIMessages: AIMessage[] = [
  {
    id: 'aim_01',
    lead_id: 'ld_01',
    tone: 'Professional',
    subject: 'Following up on our discovery call',
    body: "Hi Sarah,\n\nThanks again for the great conversation last week. As promised, I've put together a tailored overview of how LeadPilot can support Acme Robotics' sales ops team — particularly around the proposal-stage bottleneck you mentioned.\n\nWould Thursday at 2pm work for a 20-minute walkthrough?\n\nBest,\nAlex",
    created_at: daysAgo(1),
  },
];

export const seedActivity: ActivityLog[] = [
  { id: 'act_01', lead_id: 'ld_03', actor_name: 'Alex Rivera', action: 'Lead created', detail: 'Priya Desai · Harbor Health', created_at: daysAgo(1) },
  { id: 'act_02', lead_id: 'ld_02', actor_name: 'Alex Rivera', action: 'Status changed', detail: 'Qualified → Proposal Sent', created_at: daysAgo(2) },
  { id: 'act_03', lead_id: 'ld_04', actor_name: 'Alex Rivera', action: 'Task completed', detail: 'Sent pricing sheet', created_at: daysAgo(0) },
  { id: 'act_04', lead_id: 'ld_01', actor_name: 'Alex Rivera', action: 'Note added', detail: 'Sent over the proposal deck...', created_at: daysAgo(1) },
  { id: 'act_05', lead_id: 'ld_05', actor_name: 'Alex Rivera', action: 'Status changed', detail: 'Proposal Sent → Won', created_at: daysAgo(3) },
  { id: 'act_06', lead_id: 'ld_07', actor_name: 'Alex Rivera', action: 'Lead created', detail: 'Hannah Bauer · Orbitware', created_at: daysAgo(11) },
  { id: 'act_07', lead_id: 'ld_01', actor_name: 'Alex Rivera', action: 'AI message generated', detail: 'Professional tone', created_at: daysAgo(1) },
];

export const seedPlans: SubscriptionPlan[] = [
  { id: 'plan_starter', name: 'Starter', price_monthly: 29, features: ['Up to 250 leads', '50 AI messages / mo', 'Kanban + table views', 'Email support'], lead_limit: 250, ai_messages_limit: 50 },
  { id: 'plan_growth', name: 'Growth', price_monthly: 79, features: ['Up to 2,500 leads', '500 AI messages / mo', 'Custom pipeline stages', 'Team seats (up to 5)', 'Priority support'], lead_limit: 2500, ai_messages_limit: 500 },
  { id: 'plan_scale', name: 'Scale', price_monthly: 199, features: ['Unlimited leads', 'Unlimited AI messages', 'Advanced automations', 'Unlimited seats', 'Dedicated CSM'], lead_limit: null, ai_messages_limit: null },
];